AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
    Function:
        Timeout: 20

Metadata:
  AWS::ServerlessRepo::Application:
    Name: eks-ami-info
    Description: "Return the latest Amazon EKS-optimized AMI ID"
    Author: Pahud Hsieh
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['eks','lambda','ami']
    HomePageUrl: https://github.com/pahud/eks-templates/lambda/eks-ami-info
    SemanticVersion: 1.0.0-beta1
    SourceCodeUrl: https://github.com/pahud/eks-templates/lambda/eks-ami-info

Parameters:
  ClusterVersion:
    Type: String
    Default: latest

Resources:
    GetAMIInfo:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ./
            Handler: app.lambda_handler
            Runtime: python3.6
            Environment: 
                Variables:
                    ClusterVersion: !Ref ClusterVersion
            Role: !GetAtt GetAMIInfoRole.Arn
            # Policies:
            #     - EC2DescribePolicy: {}
            #     - AMIDescribePolicy: {}
                
    GetAMIInfoRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - lambda.amazonaws.com
              Action:
              - sts:AssumeRole
          Path: "/"
          Policies:
          - PolicyName: root
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                - ec2:DescribeImages
                Resource: "*"
            

    AMIInfo:
        Type: Custom::AMIInfo
        Properties:
          ServiceToken: !GetAtt GetAMIInfo.Arn
          ClusterVersion: !Ref ClusterVersion
        #   ForceUpdateAMI: !Ref ForceUpdateAMI

Outputs:
  StackName:
    Value: !Ref AWS::StackName
  Region:
    Value: !Ref AWS::Region
  AmiId:
    Value:
      !GetAtt AMIInfo.Id
    Description: "latest ID for Amazon EKS-Optimized AMI - see https://amzn.to/2H47ArB"
  LambdaExecutionRoleArn:
    Value:
      !GetAtt GetAMIInfoRole.Arn
    Description: LambdaExecutionRole Arn
